title: All about Coffee ☕
author: dneimke
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This blog is going to contain my life's knowledge about drinking coffee ☕

# social links
twitter_username: digory # DO NOT include the @ character, or else the build will fail!
github_username:  dneimke # DO NOT include the @ character, or else the build will fail!

theme: minima
show_excerpts: true # set to false to remove excerpts on the homepage
